NutriLink/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('apps.accounts.urls')),
    path('patients/', include('apps.patients.urls')),
    path('foods/', include('apps.foods.urls')),
    path('appointments/', include('apps.appointments.urls')),
    path('', lambda request: redirect('accounts:login')), # Levantamiento inicial para tests

]

apps/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('registro/', views.registro, name='registro'),
    path('login/', views.login, name='login'),
    path('perfil/', views.perfil, name='perfil'),
    path('dashboard/', views.dashboard, name='dashboard'),

]

apps/accounts/models.py
from django.db import models

# Create your models here.

apps/accounts/views.py
import requests
from django.shortcuts import render, redirect
from django.contrib import messages
# Create your views here.

def registro(request):
    if request.method == 'POST':
        # Traer datos del formulario
        rut = request.POST.get('rut', '').replace('.', '').replace('-', '').strip()
        dv = request.POST.get('dv', '').strip().upper()  # Dígito verificador por separado
        
        data = {
            "rut_nutricionista": rut,
            "dv": dv,
            "primer_nombre": request.POST.get('primerNombre'),
            "apellido_paterno": request.POST.get('apellidoP'),
            "correo": request.POST.get('email'),
            "contrasena": request.POST.get('contraseña'),
            # Campos opcionales explicitamente como None si son vacios
            "segundo_nombre": None,
            "apellido_materno": None,
            "fecha_nacimiento": None,
            "foto": None,
            "telefono": None
        }

        try:
            response = requests.post(
                "https://nutrilinkapi-production.up.railway.app/api_nutrilink/nutricionista/registrar",
                json=data,
                timeout=4
            )

            if response.status_code == 201:
                messages.success(request, '¡Registro exitoso!')
                return redirect('accounts:perfil')
            else:
                error_msg = response.json().get('error', 'Error desconocido')
                messages.error(request, f'Error: {error_msg}')
                
        except requests.exceptions.RequestException as e:
            messages.error(request, 'Error al conectar con el servidor')

    return render(request, 'accounts/registro.html')


def perfil(request):
    url = 'https://nutrilinkapi-production.up.railway.app/api_nutrilink/nutricionista/especialidades'
    especialidades = []

    try:
        response = requests.get(url)
        if response.status_code == 200:
            data = response.json()
            especialidades = data

    except requests.exceptions.RequestException as e:
        print("Error:", e)

    context = {
        'especialidades': especialidades, 
    }
    return render(request, 'accounts/perfil.html', context)

def login(request):
    return render(request, 'accounts/login.html')

def dashboard(request):
    return render(request, 'accounts/dashboard.html')

apps/accounts/templates/accounts/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Dashboard{% endblock %}

{% block content %}
<div class="container-dash">
    <div class="row mb-4">
        <!-- Gráficos (70%) -->
        <div class="col-lg-7 mt-3" >
            <div class="encabezado-dash">
                <div class="card-body" style="padding: 15px;">
                    <div>
                        <h4 id="saludo-nutricionista" class="mb-1"><i class="fas fa-heartbeat me-2"></i>Bienvenido/a, <span id="nombre-nutricionista" class="me-3">Cargando...</span></h4>
                        <p class="mb-0">NutriLink - Tu sistema de gestión nutricional</p>
                    </div>
                </div>
            </div>
            <h4 class="mt-4">Resumen de Pacientes</h4>
            <div class="row mt-4">
                <div class="col-md-6 mb-4">
                    <div class="graph-placeholder" id="total-pacientes" >
                        <!-- Card para total de pacientes -->
                    </div>
                </div>
                <div class="col-md-6 mb-4">
                    <div class="graph-placeholder" id="total-minutas" >
                        <!-- Card para total de minutas -->
                    </div>
                </div>
            </div>

            <div class="row mt-4">
                <div class="col-md-6 mb-4">
                    <div class="graph-placeholder" id="grafico-genero" >
                        <!-- Gráfico de género dinámico -->
                    </div>
                </div>
                <div class="col-md-6 mb-4">
                    <div class="graph-placeholder" id="grafico-edad">
                        <!-- Gráfico de edad dinámico-->
                    </div>
                </div>
            </div>
            <h4 class="mt-4">Resumen de Minutas</h4>
            <div class="row mt-4">
                <div class="col-12">
                    <div class="graph-placeholder" style="min-height: 400px;" id="grafico-detallado">
                        <!-- Gráfico de evolución de minutas por mes -->
                    </div>
                </div>
            </div>
        </div>
        <!-- Columna derecha (30% - Citas) -->
        <div class="col-lg-5 mt-3">
            <div class="card-citas-del-dia">
                <div class="card-header-citas">
                    <h5 class="mb-0"><i class="far fa-calendar-alt me-2"></i>Tus citas de hoy</h5>
                    <span id="fecha-hoy" class="badge bg-primary fs-6 mt-1"></span>
                    <div class="form-text text-muted mt-2">
                        <i class="fas fa-info-circle me-1"></i>Puedes cancelar o marcar como completada una cita desde la sección Agenda.
                    </div>
                </div>
                <div class="card-body mt-2" id="citas-container">
                    <!-- Las citas se generan dinámicamente -->
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<!--CDN ultima versión de plotly-->
<script src="https://cdn.plot.ly/plotly-3.0.1.min.js" charset="utf-8"></script>
<script src="{% static 'accounts/js/dashboard.js' %}"></script>
{% endblock %}

apps/accounts/templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login - NutriLink</title>
    <link rel="stylesheet" href="{% static 'accounts/css/login2.css' %}">
</head>
<body>
    <main class="login-page">
        <div class="brand-section">
            <div class="logo">
                <img src="{% static 'img/NutrilinkLOGO.svg' %}" alt="logo nutrilink">
            </div>
        </div>
        <div class="login-container">
            <div class="form-section">
                <div class="form-container">
                    <div class="welcome-header">
                        <h2>Bienvenido!</h2>
                        <img class="welcome-icon" src="{% static 'accounts/img/waving-hand-noto.svg' %}" alt="Welcome icon">
                    </div>
                    <p class="subtitle">Gestiona tus consultas nutricionales con NutriLink.</p>
                    <form id="login-form" class="login-form" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="form-label" for="emailLogin">Correo:</label>
                            <input class="form-control" type="email" id="emailLogin" name="emailLogin" placeholder="Ingresar correo">
                            <span class="error-message" id="error-emailLogin"></span>
                        </div>
                        <div class="form-group">
                            <label class="form-label" for="contraseñaLogin">Contraseña:</label>
                            <input class="form-control" type="password" id="contraseñaLogin" name="contraseñaLogin" placeholder="Ingresar contraseña">
                            <span class="error-message" id="error-contraseñaLogin"></span>
                        </div>
                        <button type="submit" class="login-btn">INICIAR SESIÓN</button>
                        <div class="remember-me">
                            <input type="checkbox" id="remember_me">
                            <label for="remember">Recordar sesión</label>
                        </div>
                    </form>
                    <p class="register-link">
                        ¿No tienes cuenta? <a href="{% url 'accounts:registro' %}">Regístrate</a>
                    </p>
                </div>
            </div>
        </div>
    </main>
</body>
<!-- SweetAlert2 -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="{% static 'accounts/js/login.js' %}"></script>
</html>

apps/accounts/templates/accounts/perfil.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Perfil{% endblock %}

{% block content %}
<main class="cards-wrapper d-flex p-4">
  <!-- Card1 Perfil -->
  <div class="form-sectionP ms-3">
    <div class="profile-picture">
      <div class="user-icon-container" id="userIconContainer">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" style="fill: rgb(206, 206, 206);">
          <path d="M12 2C6.579 2 2 6.579 2 12s4.579 10 10 10 10-4.579 10-10S17.421 2 12 2zm0 5c1.727 0 3 1.272 3 3s-1.273 3-3 3c-1.726 0-3-1.272-3-3s1.274-3 3-3zm-5.106 9.772c.897-1.32 2.393-2.2 4.106-2.2h2c1.714 0 3.209.88 4.106 2.2C15.828 18.14 14.015 19 12 19s-3.828-.86-5.106-2.228z"></path>
        </svg>
      </div>
      <img src="" id="profilePhoto" alt="Foto de perfil" style="display: none;" />
      
      <!-- Campo para subir nueva imagen -->
      <div class="mb-3 mt-3">
        <label for="imagenPerfil" class="form-label">Cambiar foto de perfil</label>
        <input type="file" class="form-control" id="imagenPerfil" name="imagenPerfil" accept="image/*">
        <span class="error-message" id="error-imagenPerfil"></span>
      </div>
    </div>
    <div class="form-containerP">
      <div class="d-flex text-center justify-content-between mb-3">
        <h3>Mi Perfil</h3>
      </div>
      <form class="perfil-form" id="profile-form" method="POST">
        {% csrf_token %}
        <div class="row">
          <div class="form-group col-md-6 mb-4">
            <label for="pNombre">Primer nombre<span class="required">*</span></label>
            <input type="text" id="pNombre" name="pNombre" class="form-control" placeholder="nombre" />
            <span class="error-message" id="error-pNombre"></span>
          </div>
          <div class="form-group col-md-6 mb-3">
            <label for="sNombre">Segundo nombre </label>
            <input type="text" id="sNombre" name="sNombre" class="form-control" placeholder="nombre" />
            <span class="error-message" id="error-sNombre"></span>
          </div>
          <div class="form-group col-md-6 mb-3">
            <label for="apePater">Apellido paterno<span class="required">*</span></label>
            <input type="text" id="apePater" name="apePater" class="form-control" placeholder="apellido" />
            <span class="error-message" id="error-apePater"></span>
          </div>
          <div class="form-group col-md-6 mb-3">
            <label for="apeMater">Apellido materno</label>
            <input type="text" id="apeMater" name="apeMater" class="form-control" placeholder="apellido" />
            <span class="error-message" id="error-apeMater"></span>
          </div>
          <div class="form-group col-md-6 mb-3">
            <label for="email">Correo<span class="required">*</span></label>
            <input type="email" id="email" name="email" class="form-control" placeholder="correo" disabled />
            <span class="error-message" id="error-email"></span>
          </div>
          <div class="form-group col-md-6 mb-3">
            <label for="rut">RUT<span class="required">*</span></label>
            <input type="text" id="rut" name="rut" class="form-control" placeholder="Rut" disabled />
            <span class="error-message" id="error-rut"></span>
          </div>
          <div class="form-group col-md-6 mb-3">
            <label for="fechaNacimiento">Fecha de nacimiento:</label>
            <input type="date" id="fechaNacimiento" name="fechaNacimiento" class="form-control" />
            <span class="error-message" id="error-fechaNacimiento"></span>
          </div>
          <div class="form-group col-md-6 mb-3">
            <label for="telefono">Teléfono:</label>
            <input type="text" id="telefono" name="telefono" class="form-control" placeholder="Número de contacto" />
            <span class="error-message" id="error-telefono"></span>
          </div>
        </div>
        <button class="btn btn-success w-100" type="submit">Actualizar</button>
      </form>
    </div>
  </div>
  <!-- Cards laterales, especializacion -->
  <div class="d-flex flex-column flex-shrink-1">
    <div
      style="background-color: white; border-radius: 15px; box-shadow: 0 4px 20px rgba(0, 0, 0, 0.15);; padding: 1.5rem;"
      class="mb-3">
      <div class="title mb-3">
        <h5>Especialización</h5>
      </div>
      <form id="especializacion-form" method="POST">
        {% csrf_token %}
        <div class="selection-group">
          <div class="form-group mb-3">
            <label for="especializacion">Especialidad:</label>
            <select id="especializacion" name="especializacion" class="form-select">
              <option value="" selected disabled>Selecciona tus especialidades</option>
              {% for esp in especialidades %}
              <option value="{{ esp.id_especialidad }}">{{ esp.descripcion }}</option>
              {% endfor %}
            </select>
            <span class="error-message" id="error-especializacion"></span>
          </div>
          <div class="selected-items-container" id="especialidades-container"></div>
        </div>
        <div class="text-center">
          <button class="btn btn-success w-50 mt-3" type="submit">Guardar</button>
        </div>    
      </form>
    </div>
    <!-- Cambiar contraseña -->
    <div
      style="background-color: white; border-radius: 15px; box-shadow: 0 4px 20px rgba(0, 0, 0, 0.15); padding: 1.5rem;"
      class="mb-3">
      <div class="title mb-3">
        <h5>Cambiar contraseña</h5>
      </div>
      <form id="password-form" method="POST">
        {% csrf_token %}
        <div class="form-group mb-3">
          <label for="passActual">Contraseña actual:<span class="required">*</span></label>
          <input type="password" id="passActual" name="passActual" class="form-control" placeholder="********"
            required />
          <span class="error-message" id="error-passActual"></span>
        </div>
        <div class="form-group mb-3">
          <label for="passNueva">Nueva contraseña:</label>
          <input type="password" id="passNueva" name="passNueva" class="form-control" placeholder="********" required />
          <span class="error-message" id="error-passNueva"></span>
        </div>
        <div class="form-group mb-3">
          <label for="confirmarPass">Confirmar contraseña:</label>
          <input type="password" id="confirmarPass" name="confirmarPass" class="form-control" placeholder="********"
            required />
          <span class="error-message" id="error-confirmarPass"></span>
        </div>
        <div class="text-center">
          <button class="btn btn-success w-50" type="submit">Actualizar contraseña</button>
        </div>
      </form>
    </div>
    <!-- Centros de Atención Registrados -->
    <div id="centros-container"
      style="background-color: white; border-radius: 15px; box-shadow: 0 4px 20px rgba(0, 0, 0, 0.15); padding: 1.5rem;"
      class="mb-3">
      <div class="title mb-3">
        <h5>Centros de atención</h5>
      </div>
      <!-- Aquí se insertarán dinámicamente los centros desde JavaScript -->
      <div id="lista-centros">
        <p class="text-muted">Cargando centros registrados...</p>
      </div>
      <!-- Botón para abrir el modal -->
      <div class="text-center mt-3">
        <button class="btn btn-success mt-2 w-50" data-bs-toggle="modal" data-bs-target="#modalAgregarCentro">
          + Agregar centro de atención
        </button>
      </div>
      <!-- Modal para registrar centro de atención -->
      <div class="modal fade" id="modalAgregarCentro" tabindex="-1" aria-labelledby="modalAgregarCentroLabel"
        aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <form id="form-agregar-centro">
              <input type="hidden" id="idCentroEditar" />
              <div class="modal-header">
                <h5 class="modal-title" id="modalAgregarCentroLabel">Agregar centro de atención</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
              </div>
              <div class="modal-body">
                <div class="mb-3">
                  <label for="nombreCentro" class="form-label">Nombre del centro</label>
                  <input type="text" class="form-control" id="nombreCentro" name="nombreCentro" required />
                  <div class="invalid-feedback" id="error-nombreCentro"></div>
                </div>
                <div class="mb-3">
                  <label for="direccionCentro" class="form-label">Dirección</label>
                  <input type="text" class="form-control" id="direccionCentro" name="direccionCentro" required />
                  <div class="invalid-feedback" id="error-direccionCentro"></div>
                </div>
              </div>
              <div class="modal-footer">
                <button type="submit" class="btn btn-success">Registrar</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

{% block scripts %}
<script src="{% static 'accounts/js/perfil.js' %}"></script>
{% endblock %}

apps/accounts/templates/accounts/registro.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro - NutriLink</title>
    <link rel="stylesheet" href="{% static 'accounts/css/registro2.css' %}">
</head>
<body>
    <!-- LOGO -->
    <main class="registro-page">
        <div class="brand-section">
            <div class="logo">
                <img src="{% static 'img/NutrilinkLOGO.svg' %}" alt="Logo de nutrilink">
            </div>
        </div>
        <!-- Seccion bienvenida registro -->
        <div class="container">
            <div class="card">
                <h2 class="title">Regístrate y potencia tus consultas!</h2>
                <p class="subtitle">Comienza a usar nuestra plataforma hoy mismo</p>
                <ul class="benefits">
                    <li> 
                        <img src="{% static 'accounts/img/tick-mark-icon.svg' %}" alt="Visualiza progreso" />
                        Visualiza el progreso de tus pacientes en gráficos.</li>
                    <li> 
                        <img src="{% static 'accounts/img/tick-mark-icon.svg' %}" alt="Visualiza progreso" />
                        Calcula requerimientos calóricos y macronutrientes en segundos.</li>
                    <li> 
                        <img src="{% static 'accounts/img/tick-mark-icon.svg' %}" alt="Visualiza progreso" />
                        Genera minutas rápidamente y más!</li>
                </ul>
                <form id="registro-form" method="POST">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="form-col">
                            <div class="form-group">
                                <label for="primerNombre">Primer nombre:<span class="required">*</span></label>
                                <input type="text" id="primerNombre" name="primerNombre" class="form-control" placeholder="Ingresar nombre">
                                <span class="error-message" id="error-primerNombre"></span>
                            </div>
                        </div>
                        <div class="form-col">
                            <div class="form-group">
                                <label for="apellidoP">Primer apellido:<span class="required">*</span></label>
                                <input type="text" id="apellidoP" name="apellidoP" class="form-control" placeholder="Ingresar apellido">
                                <span class="error-message" id="error-apellidoP"></span>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-col" style="flex: 2;">
                            <div class="form-group">
                                <label for="rut">Rut:<span class="required">*</span></label>
                                <input style="font-size: small;" type="text" id="rut" name="rut" class="form-control" placeholder="Rut sin puntos y guión" maxlength="8">
                                <span class="error-message" id="error-rut"></span>
                            </div>
                        </div>
                        <span style="font-size: 1.5rem; padding-top: 30px;">-</span>
                        <div class="form-col" style="flex: 1;">
                            <div class="form-group">
                                <label for="id">Verificador:<span class="required">*</span></label>
                                <input  type="text" id="dv" name="dv" class="form-control" placeholder="Digito" maxlength="1">
                                <span class="error-message" id="error-dv"></span>
                            </div>
                        </div>
                        <div class="form-col">
                            <div class="form-group">
                                <label for="email">Correo:<span class="required">*</span></label>
                                <input type="email" id="email" name="email" class="form-control" placeholder="Ingresar correo">
                                <span class="error-message" id="error-email"></span>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-col">
                            <div class="form-group">
                                <label for="contraseña">Contraseña:<span class="required">*</span></label>
                                <input type="password" id="contraseña" name="contraseña" class="form-control" placeholder="Ingresar contraseña">
                                <span class="error-message" id="error-contraseña"></span>
                            </div>
                        </div>
                        <div class="form-col">
                            <div class="form-group">
                                <label for="confirmarC">Confirmar contraseña:<span class="required">*</span></label>
                                <input type="password" id="confirmarC" name="confirmarC" class="form-control" placeholder="Confirmar contraseña">
                                <span class="error-message" id="error-confirmarC"></span>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn-register">REGISTRARSE</button>
                </form>
                <p class="login-link">Ya tienes cuenta? <a href="{% url 'accounts:login' %}">Iniciar sesión</a></p>
            </div>
        </div>
    </main>
</body>
<!-- SweetAlert2 -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    // Define las URLs de Django como variables globales
    const LOGIN_URL = "{% url 'accounts:login' %}";
</script>
<script src="{% static 'accounts/js/registro.js' %}"></script>
</html>