NutriLink/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('apps.accounts.urls')),
    path('patients/', include('apps.patients.urls')),
    path('foods/', include('apps.foods.urls')),
    path('appointments/', include('apps.appointments.urls')),
    path('', lambda request: redirect('accounts:login')), # Levantamiento inicial para tests

]

apps/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('registro/', views.registro, name='registro'),
    path('login/', views.login, name='login'),
    path('perfil/', views.perfil, name='perfil'),
    path('dashboard/', views.dashboard, name='dashboard'),

]

apps/appointments/urls.py
from django.urls import path
from . import views

app_name = 'appointments'

urlpatterns = [
    path('', views.bdCrud, name='appointments'),
]

apps/foods/urls.py
from django.urls import path
from . import views

app_name = 'foods'

urlpatterns = [
    path('foods/', views.bdCrud, name='bdCrud'),

]

apps/patients/urls.py
from django.urls import path
from . import views

app_name = 'patients'

urlpatterns = [
    path('gestion/', views.gestion, name='gestion'),
    path('<int:id_paciente>/historial-clinico/', views.historialClinico, name='historial-clinico'),
    path('<int:id_paciente>/metricas/', views.metricas, name='metricas'),
    path('<int:id_paciente>/info-general/', views.infoGeneral, name='info-general'),
    path('<int:id_paciente>/registro-dietario/', views.registroDietario, name='registro-dietario'),
    path('<int:id_paciente>/grafico_adecuacion_dieta/', views.grafico_adecuacion_dieta_ajax, name='grafico_adecuacion_dieta_ajax'),
    path('<int:id_paciente>/minuta/', views.minuta, name='minuta'),
    path('info-general/<int:id_paciente>/enviar_credenciales/', views.enviar_credenciales, name='enviar_credenciales'),
    path('<int:id_paciente>/enviar_minuta_por_correo/', views.enviar_minuta_por_correo, name='enviar_minuta_por_correo'),
]

apps/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{% block title %}{% endblock %} - NutriLink</title>
  
  <link href="{% static 'css/sidebar.css' %}" rel="stylesheet" />
  <link href="{% static 'css/navbar.css' %}" rel="stylesheet" />
  <link href="{% static 'accounts/css/perfil.css' %}" rel="stylesheet" />
  <link href="{% static 'patients/css/gestion.css' %}" rel="stylesheet" />
  <link href="{% static 'foods/css/bdCrud.css' %}" rel="stylesheet" />
  <link href="{% static 'accounts/css/dashboard.css' %}" rel="stylesheet" />

  <!--cdn sweet alert-->
  <link href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css" rel="stylesheet">
   <!--cdn bootstrap-->
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
   integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <!--cdn bootstrap icons-->
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
   <!--cdn js-->
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
   <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
   <!-- plotly -->
   <script src="https://cdn.plot.ly/plotly-3.0.1.min.js"></script> 
</head>
<body>
  <!-- Sidebar -->
  {% block sidebar %}
  <div class="side-bar">
    <div class="logo-container">
      <img src="{% static 'img/NutrilinkLOGO.svg' %}" alt="Logo de Nutrilink" class="sidebar-logo" />
    </div>
    <div class="menu">
    <a href="{% url 'accounts:dashboard' %}" 
       class="btn {% if request.resolver_match.url_name == 'dashboard' %}active{% endif %}" 
       style="display: flex; align-items: center;">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="fill: rgb(255, 255, 255);">
            <path d="M4 13h6a1 1 0 0 0 1-1V4a1 1 0 0 0-1-1H4a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1zm-1 7a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1v-4a1 1 0 0 0-1-1H4a1 1 0 0 0-1 1v4zm10 0a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1v-7a1 1 0 0 0-1-1h-6a1 1 0 0 0-1 1v7zm1-10h6a1 1 0 0 0 1-1V4a1 1 0 0 0-1-1h-6a1 1 0 0 0-1 1v5a1 1 0 0 0 1 1z"></path>
        </svg>
        <span style="margin-left: 8px;">Dashboard</span>
    </a>
    
    <a href="{% url 'patients:gestion' %}" 
       class="btn {% if request.resolver_match.url_name == 'gestion' and request.resolver_match.app_name == 'patients' %}active{% endif %}" 
       style="display: flex; align-items: center;">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="fill: rgb(255, 255, 255);">
            <path d="M6 22h13a2 2 0 0 0 2-2V4a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h1zm6-17.001c1.647 0 3 1.351 3 3C15 9.647 13.647 11 12 11S9 9.647 9 7.999c0-1.649 1.353-3 3-3zM6 17.25c0-2.219 2.705-4.5 6-4.5s6 2.281 6 4.5V18H6v-.75z"></path>
        </svg>
        <span style="margin-left: 8px;">Pacientes</span>
    </a>
    
    <a href="{% url 'appointments:appointments' %}" 
       class="btn {% if request.resolver_match.url_name == 'appointments' %}active{% endif %}" 
       style="display: flex; align-items: center;">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="fill: rgb(255, 255, 255);">
            <path d="M7 11h2v2H7zm0 4h2v2H7zm4-4h2v2h-2zm0 4h2v2h-2zm4-4h2v2h-2zm0 4h2v2h-2z"></path>
            <path d="M5 22h14c1.103 0 2-.897 2-2V6c0-1.103-.897-2-2-2h-2V2h-2v2H9V2H7v2H5c-1.103 0-2 .897-2 2v14c0 1.103.897 2 2 2zM19 8l.001 12H5V8h14z"></path>
        </svg>
        <span style="margin-left: 8px;">Agenda</span>
    </a>
    
    <a href="{% url 'foods:bdCrud' %}" 
       class="btn {% if request.resolver_match.url_name == 'bdCrud' %}active{% endif %}" 
       style="display: flex; align-items: center;">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="fill: rgb(255, 255, 255);">
            <path d="M20 6c0-2.168-3.663-4-8-4S4 3.832 4 6v2c0 2.168 3.663 4 8 4s8-1.832 8-4V6zm-8 13c-4.337 0-8-1.832-8-4v3c0 2.168 3.663 4 8 4s8-1.832 8-4v-3c0 2.168-3.663 4-8 4z"></path>
            <path d="M20 10c0 2.168-3.663 4-8 4s-8-1.832-8-4v3c0 2.168 3.663 4 8 4s8-1.832 8-4v-3z"></path>
        </svg>
        <span style="margin-left: 8px;">Alimentos</span>
    </a>
  </div>
  </div>
  {% endblock %}

  {% block nav %}
  <!-- Navbar -->
  <div class="navbar text-white px-4 py-2">
    <div class="d-flex justify-content-between align-items-center w-100">
      <span class="me-3"></span>
        
        <div class="dropdown profile-dropdown">
          <button class="btn dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="fill: rgb(255, 255, 255);"><path d="M12 2C6.579 2 2 6.579 2 12s4.579 10 10 10 10-4.579 10-10S17.421 2 12 2zm0 5c1.727 0 3 1.272 3 3s-1.273 3-3 3c-1.726 0-3-1.272-3-3s1.274-3 3-3zm-5.106 9.772c.897-1.32 2.393-2.2 4.106-2.2h2c1.714 0 3.209.88 4.106 2.2C15.828 18.14 14.015 19 12 19s-3.828-.86-5.106-2.228z"></path></svg>
            Perfil
          </button>
          <ul class="dropdown-menu dropdown-menu-end">
            <li><a class="dropdown-item" href="{% url 'accounts:perfil' %}">Mi cuenta</a></li>
            <li><a class="dropdown-item" href="#" id="logout-link">Cerrar sesión</a></li>
            <li><hr class="dropdown-divider" /></li>
            <li><a class="dropdown-item" href="#" id="eliminar-cuenta">Eliminar cuenta</a></li>
          </ul>
        </div>
    </div>
</div>
  {% endblock %}

  {% block content %}{% endblock %}
  <!-- Sweet alert JS -->
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  <!-- Bootstrap JS -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>

  <script src="{% static '/js/base.js' %}"></script>
  <script>
    // URLs de Django como variables globales
    const LOGIN_URL = "{% url 'accounts:login' %}";
  </script>
{% block scripts %}{% endblock %}
</body>
</html>