NutriLink/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('apps.accounts.urls')),
    path('patients/', include('apps.patients.urls')),
    path('foods/', include('apps.foods.urls')),
    path('appointments/', include('apps.appointments.urls')),
    path('', lambda request: redirect('accounts:login')), # Levantamiento inicial para tests

]

apps/patients/urls.py
from django.urls import path
from . import views

app_name = 'patients'

urlpatterns = [
    path('gestion/', views.gestion, name='gestion'),
    path('<int:id_paciente>/historial-clinico/', views.historialClinico, name='historial-clinico'),
    path('<int:id_paciente>/metricas/', views.metricas, name='metricas'),
    path('<int:id_paciente>/info-general/', views.infoGeneral, name='info-general'),
    path('<int:id_paciente>/registro-dietario/', views.registroDietario, name='registro-dietario'),
    path('<int:id_paciente>/grafico_adecuacion_dieta/', views.grafico_adecuacion_dieta_ajax, name='grafico_adecuacion_dieta_ajax'),
    path('<int:id_paciente>/minuta/', views.minuta, name='minuta'),
    path('info-general/<int:id_paciente>/enviar_credenciales/', views.enviar_credenciales, name='enviar_credenciales'),
    path('<int:id_paciente>/enviar_minuta_por_correo/', views.enviar_minuta_por_correo, name='enviar_minuta_por_correo'),
]

apps/patients/models.py
from django.db import models

# Create your models here.

apps/patients/views.py
from django.shortcuts import redirect, render
import requests
from django.conf import settings
from django.http import Http404, JsonResponse, HttpResponse
from datetime import datetime
from django.core.cache import cache #futuro: para almacenar peticiones en cache por un tiempo def
from requests.exceptions import RequestException
from django.core.mail import send_mail, EmailMultiAlternatives # Para enviar emails
from django.contrib import messages  # Para mostrar alertas en el template
import json
import plotly.express as px
import plotly.io as pio
import pandas as pd

# Create your views here.
def gestion(request):
    print("BASE_DIR:", settings.BASE_DIR)
    return render(request, 'patients/gestion.html')
    
def get_paciente_data(id_paciente):
    try:
        api_url = f'https://nutrilinkapi-production.up.railway.app/api_nutrilink/paciente/perfil/{id_paciente}'
        response = requests.get(api_url, timeout=10)
        
        if response.status_code == 404:
            raise Http404("Paciente no encontrado")
        response.raise_for_status()
        
        paciente_data = response.json()
        fecha_nac = datetime.strptime(paciente_data['fechanac'], "%Y-%m-%d")
        edad = datetime.now().year - fecha_nac.year
        
        nombres = [paciente_data['primer_nombre']]
        if paciente_data.get('segundo_nombre'):
            nombres.append(paciente_data['segundo_nombre'])
        
        apellidos = [paciente_data['apellido_paterno']]
        if paciente_data.get('apellido_materno'):
            apellidos.append(paciente_data['apellido_materno'])
        
        nombre_completo = ' '.join(nombres + apellidos).strip()

        iniciales = (paciente_data['primer_nombre'][0].upper() if paciente_data['primer_nombre'] else '') + \
                    (paciente_data['apellido_paterno'][0].upper() if paciente_data['apellido_paterno'] else '')

        paciente_data['iniciales'] = iniciales  # Se agregan las iniciales al diccionario
        paciente_data['avatar_url'] = f"https://ui-avatars.com/api/?name={iniciales}&background=random&color=fff&size=200"
        
        return {
            'id_paciente': paciente_data['id_paciente'],
            'nombre_completo': nombre_completo if nombre_completo else ' ',
            'rut_paciente': f"{paciente_data['rut_paciente']}-{paciente_data['dv']}",
            'edad': edad,
            'sexo': 'Masculino' if paciente_data['sexo'] == 'M' else 'Femenino',
            'telefono': paciente_data.get('telefono'),
            'correo': paciente_data['correo'],
            'fecha_nacimiento': paciente_data['fechanac'],
            'iniciales': iniciales,  # Añade esto
            'avatar_url': paciente_data['avatar_url'] # Añade esto
        }
    except requests.Timeout:
        raise Http404("Tiempo de espera agotado al conectar con la API")
    except requests.RequestException as e:
        raise Http404(f"Error al obtener datos del paciente: {str(e)}")
    except (ValueError, KeyError) as e:
        raise Http404(f"Error en los datos: {str(e)}")

def historialClinico(request, id_paciente):
    try:
        paciente = get_paciente_data(id_paciente)
        success, factores_patologicos, error = get_factores_patologicos()
        niveles_actividad = get_niveles_actividad_fisica()
        alimentos = get_alimentos()

        if not success:
            return render(request, 'patients/historial-clinico.html', {
                'paciente': paciente,
                'factores_patologicos': [],
                'error_factores': error,
                'niveles_actividad': niveles_actividad,
                'alimentos': alimentos,
                'section': 'historial-clinico'
            })

        return render(request, 'patients/historial-clinico.html', {
            'paciente': paciente,
            'factores_patologicos': factores_patologicos,
            'niveles_actividad': niveles_actividad,
            'alimentos': alimentos,
            'section': 'historial-clinico'
        })

    except Exception as e:
        print(f"Error en historialClinico: {str(e)}")
        raise Http404(f"Error al cargar historial clínico: {str(e)}")

def metricas(request, id_paciente):
    paciente = get_paciente_data(id_paciente)
    historial = get_historial_antropometrico(id_paciente)

    fechas_disponibles = sorted(list(set([registro['fecha'] for registro in historial if 'fecha' in registro])))

    fecha_seleccionada = request.GET.get('fecha')
    diagnosticos = None

    if fecha_seleccionada:
        diagnosticos = get_diagnosticos_antropometricos(id_paciente, fecha_seleccionada)

    # Preparar datos para los gráficos siempre que haya historial
    graficos_data = None
    if historial:
        # Convertir el historial a DataFrame
        df = pd.DataFrame(historial)

        # Convertir las columnas numéricas de string a float
        numeric_cols = ['peso_kg', 'talla_cm', 'porc_grasa']
        for col in numeric_cols:
            if col in df.columns:
                df[col] = pd.to_numeric(df[col], errors='coerce')  # Convierte a número, inválidos a NaN

        # Convertir la fecha a datetime
        df['fecha'] = pd.to_datetime(df['fecha'], errors='coerce')

        # Calculamos IMC si tenemos peso y talla
        if 'peso_kg' in df.columns and 'talla_cm' in df.columns:
            df['imc'] = df['peso_kg'] / ((df['talla_cm']/100)**2)

        # Eliminar filas con fechas inválidas
        df = df.dropna(subset=['fecha'])

        # Ordenar por fecha
        df = df.sort_values('fecha')

        # Crear gráficos
        graficos_data = {
            'imc': crear_grafico_evolucion(df, 'fecha', 'imc', 'IMC (kg/m²)'),
            'peso': crear_grafico_evolucion(df, 'fecha', 'peso_kg', 'Peso (kg)'),
            'grasa': crear_grafico_evolucion(df, 'fecha', 'porc_grasa', '% Grasa corporal'),
        }

    return render(request, 'patients/metricas.html', {
        'paciente': paciente,
        'historial_antropometrico': historial,
        'diagnosticos_data': diagnosticos,
        'fecha_seleccionada': fecha_seleccionada,
        'fechas_disponibles': fechas_disponibles,
        'graficos_data': graficos_data,
        'section': 'metricas'
    })


def crear_grafico_evolucion(df, x_col, y_col, title):
    """Graficos de linea"""
    if y_col not in df.columns:
        return None

    # Filtrar datos válidos
    df_plot = df.dropna(subset=[x_col, y_col])
    if df_plot.empty:
        return None

    fig = px.line(
        df_plot,
        x=x_col,
        y=y_col,
        title=title,
        markers=True,
        labels={x_col: 'Fecha', y_col: title}
    )

    # Diseño
    fig.update_layout(
        plot_bgcolor='rgba(0,0,0,0)',
        paper_bgcolor='rgba(0,0,0,0)',
        xaxis=dict(
            showgrid=False,
            tickformat='%Y-%m-%d',
            # Ticks
            tickvals=df_plot[x_col].dt.strftime('%Y-%m-%d').unique().tolist(),
            ticktext=df_plot[x_col].dt.strftime('%Y-%m-%d').unique().tolist()
        ),
        yaxis=dict(showgrid=True, gridcolor='lightgray'),
        margin=dict(l=20, r=20, t=40, b=20),
        height=300
    )

    return pio.to_html(fig, full_html=False)

def minuta(request, id_paciente):
    paciente = get_paciente_data(id_paciente)
    
    return render(request, 'patients/minuta.html', {
        'paciente': paciente,
        'section': 'indicaciones'
    })
    
def registroDietario(request, id_paciente):
    paciente = get_paciente_data(id_paciente)
    
    return render(request, 'patients/registro-dietario.html', {
        'paciente': paciente,
        'section': 'registro-dietario'
    })

def infoGeneral(request, id_paciente):
    paciente = get_paciente_data(id_paciente)
    credenciales = get_credenciales(id_paciente)

    return render(request, 'patients/info-general.html', {
        'paciente': paciente,
        'credenciales': credenciales,
        'section': 'info-general'
    })

def get_credenciales(id_paciente):
    try:
        url = f'https://nutrilinkapi-production.up.railway.app/api_nutrilink/paciente/credenciales/{id_paciente}'
        response = requests.get(url)

        if response.status_code == 200:
            data = response.json()
            return {
                'correo': data.get('correo'),
                'contrasena': data.get('contrasena')
            }
        else:
            print(f'Error al obtener credenciales: {response.status_code} - {response.text}')
            return None
    except requests.RequestException as e:
        print(f'Excepción al conectar con el endpoint de credenciales: {e}')
        return None
    
def get_factores_patologicos():
    """
    Returns requeridos:
        tuple: (success: bool, data: list, error: str)
    """
    url = 'http://nutrilinkapi-production.up.railway.app/api_nutrilink/requerimientos/obtener_factor_patologico'
    timeout = 10
    
    try:
        response = requests.get(url, timeout=timeout)
        response.raise_for_status()  # excepcion para codigos 4xx/5xx
        
        data = response.json()
        
        # Verificar estructura de respuesta
        if isinstance(data, dict) and data.get('status') == 'success':
            if isinstance(data.get('data'), list):
                return True, data['data'], None
            return False, [], "Estructura de datos inesperada"
            
        return False, [], "Respuesta no exitosa o formato incorrecto"
            
    except RequestException as e:
        return False, [], f"Error de conexión: {str(e)}"
    except ValueError as e:
        return False, [], f"Error procesando JSON: {str(e)}"
    except Exception as e:
        return False, [], f"Error inesperado: {str(e)}"

def get_historial_antropometrico(id_paciente):
    try:
        url = f'https://nutrilinkapi-production.up.railway.app/api_nutrilink/paciente/obtener_antropometria/{id_paciente}'
        response = requests.get(url)

        if response.status_code == 200:
            data = response.json()

apps/patients/templates/basePerfil.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
<link href="{% static 'basePerfil.css' %}" rel="stylesheet" />
<link href="{% static 'patients/css/info-general.css' %}" rel="stylesheet" />
<link href="{% static 'patients/css/historial-clinico.css' %}" rel="stylesheet" >
<link href="{% static 'patients/css/metricas.css' %}" rel="stylesheet" >
<link href="{% static 'patients/css/minuta.css' %}" rel="stylesheet" >
<link href="{% static 'patients/css/registro-dietario.css' %}" rel="stylesheet" >

<div class="patient-profile-container">
  <!-- Card de perfil -->
  <div class="patient-card">
    <div class="profile-header">
      <div class="avatar-section">
        <img class="avatar-icon" id="userAvatar" src="{{ paciente.avatar_url }}" alt="Avatar de {{ paciente.nombre_completo }}">
        <div>
          <div class="patient-name" id="patient-name">{{ paciente.nombre_completo }}</div>
          <div class="patient-rut" id="patient-rut">RUT: {{ paciente.rut_paciente }}</div>
        </div>
      </div>
      <div class="divider"></div>
      <div class="info-section container">
        <div class="basic-info-title mb-3">Información Básica</div>
        <div class="row">
          <div class="col-md-6">
            <div class="basic-info-item"><strong>Edad: </strong> <span id="patient-age">{{ paciente.edad|default:" "  }}</span> años</div>
            <div class="basic-info-item mt-2"><strong>Género: </strong><span id="patient-gender">{{ paciente.sexo|default:" "  }}</span></div>
          </div>
          <div class="col-md-6">
            <div class="basic-info-item"><strong>Teléfono: </strong><span id="patient-phone">{{ paciente.telefono|default:"No especificado"}}</span></div>
            <div class="basic-info-item"><strong>Correo: </strong> <span id="patient-email">{{ paciente.correo  }}</span></div>
        </div>
      </div>
    </div>
  </div>
  <!-- Navbar secciones del paciente -->
  <div class="nav-buttons">
    <a href="{% url 'patients:info-general' id_paciente=paciente.id_paciente %}" class="nav-button {% if section == 'info-general' %}active{% endif %}" data-section="info-general">
      <i class="bi bi-info-circle"></i> Información general
    </a>
    <a href="{% url 'patients:historial-clinico' id_paciente=paciente.id_paciente %}" class="nav-button {% if section == 'historial-clinico' %}active{% endif %}" data-section="historial-clinico">
      <i class="bi bi-file-earmark-medical"></i> Historial clínico
    </a>
    <a href="{% url 'patients:metricas' id_paciente=paciente.id_paciente %}" class="nav-button {% if section == 'metricas' %}active{% endif %}" data-section="metricas">
      <i class="bi bi-graph-up"></i> Antropometría y requerimientos
    </a>
    <a href="{% url 'patients:registro-dietario' id_paciente=paciente.id_paciente %}" class="nav-button {% if section == 'registro-dietario' %}active{% endif %}" data-section="registro-dietario">
      <i class="bi bi-list-ul"></i> Registro dietario
    </a>
    <a href="{% url 'patients:minuta' id_paciente=paciente.id_paciente %}" class="nav-button {% if section == 'indicaciones' %}active{% endif %}" data-section="indicaciones">
      <i class="bi bi-list-check"></i> Indicaciones
    </a>
  </div>
</div>

<div class="dynamic-content-container">
  {% block perfilcontent %}
  <!-- Aquí se inserta el contenido específico de cada vista hija -->
  {% endblock %}
</div>
{% endblock %}